name: month_year_picker2
description: The month year picker inspired by the Flutter's date picker design.
version: 1.0.0+1
homepage: https://github.com/YawarOsman/month_year_picker2.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: any
